### ISSUE TITLE
Definition of KDE in paper

### ISSUE THREAD

**Issue by akalino** [chingyaoc/InfoOT#2]
Hello,

On page 3 of the associated paper (eq. 1), I believe the last term should reflect the marginal of Y and should read d_Y(y, y_i). Please let me know if this was a typo or if that was intended; if the latter, is there a reference to follow?

**Comment by chingyaoc** [comment]
Thanks for pointing this out! Yes, this is indeed a typo and it should be d_Y(y, y_i).
